### ISSUE TITLE
BL: Add buttons

### ISSUE THREAD

**Issue by itannady** [sirpuffin1/Ice-Code-#17]
Issue Template:

Description
Add "read" and "remove" icons. 

Screenshots
![image](https://user-images.githubusercontent.com/93556334/168170907-f51e834c-ff68-4931-b128-ba9c88f0d2cd.png)

Files
index.html
style.css

Tasks

[ ] Add "read" and "remove" icons to html
[ ] Style "read" icon to default gray
[ ] Add javascript to change "read" icon to green when clicked

**Comment by muhammedyucel** [comment]
Hi, I have a school assignment. Can I solve this problem of yours?
In what position exactly do you want the button?

**Comment by sirpuffin1** [comment]
Ne yazık ki, bu herkesin rol aldığı küçük bir proje, ancak sorduğunuz için teşekkür ederiz ve görevinizde iyi şanslar!

**Comment by muhammedyucel** [comment]
Anladım,teşekkürler.
